# Generated by Django 4.2.21 on 2026-10-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("revenue", "0022_remove_car_model_carcategory_model_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auction",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="carcategory",
            options={
                "ordering": ["company", "model", "-id"],
                "verbose_name_plural": "Car Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="companyaccount",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="saler",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-date", "-id"]},
        ),
    ]
