# Generated by Django 4.2.21 on 2026-10-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_user_business_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tax_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=10.0, max_digits=5, null=True
            ),
        ),
    ]
