# Generated by Django 5.0.6 on 2026-10-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0007_alter_sparepart_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="is_cash",
            field=models.BooleanField(default=False),
        ),
    ]
