# Generated by Django 4.2.21 on 2026-10-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0008_expense_is_cash"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="tax_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The calculated tax amount for this expense.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="tax_percent_used",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The tax rate (%) applied to this expense, if any.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
