# Generated by Django 4.2.21 on 2026-10-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0009_tax_rate_model_and_expense_tax_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["-date", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="expensecategory",
            options={"ordering": ["-id"], "verbose_name_plural": "Expense Categories"},
        ),
        migrations.AlterModelOptions(
            name="restaurant",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="sparepart",
            options={"ordering": ["-id"]},
        ),
    ]
